name: app
description: "MasterClass final project"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter_native_splash: ^2.4.6
  cached_network_image: ^3.3.0
  webview_flutter: ^4.4.2
  google_sign_in: ^7.1.1
  sign_in_with_apple: ^7.0.1

  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.4.2
  cupertino_icons: ^1.0.8
  animated_splash_screen: ^1.3.0
  smooth_page_indicator: ^1.1.0
  provider: ^6.1.5+1
  supabase_flutter: ^2.10.0
  http: ^1.5.0
  image_picker: ^1.0.7
  file_picker: ^10.3.3
  flutter_map: ^8.2.1
  latlong2: ^0.9.0
  location: ^8.0.1
  readmore: ^3.0.0
  firebase_core: ^4.1.0
  timezone: ^0.10.1
  flutter_dotenv: ^6.0.0
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/IntroPage1.png
    - assets/images/IntroPage3.png
    - assets/images/IntroPage2.png
    - assets/images/logo.png
    - assets/images/notificationLogo.png
    - assets/images/Apple.png
    - assets/images/Google.png
    - assets/images/Group.png
    - .env

  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
